import { IsString, IsNumber, IsEnum, IsOptional, IsArray, IsBoolean, ValidateNested, IsDateString } from 'class-validator';
import { Type } from 'class-transformer';
import { ProposalType } from '../proposal.entity';

class MilestoneDto {
  @IsString()
  title: string;

  @IsString()
  description: string;

  @IsNumber()
  amount: number;

  @IsDateString()
  dueDate: Date;
}

class AttachmentDto {
  @IsString()
  filename: string;

  @IsString()
  url: string;

  @IsString()
  type: string;

  @IsNumber()
  size: number;
}

class CustomQuestionDto {
  @IsString()
  question: string;

  @IsString()
  answer: string;
}

export class CreateProposalDto {
  @IsString()
  projectId: string;

  @IsString()
  freelancerId: string;

  @IsString()
  coverLetter: string;

  @IsOptional()
  @IsNumber()
  proposedAmount?: number;

  @IsOptional()
  @IsNumber()
  estimatedHours?: number;

  @IsOptional()
  @IsNumber()
  estimatedDays?: number;

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => MilestoneDto)
  milestones?: MilestoneDto[];

  @IsOptional()
  @IsEnum(ProposalType)
  type?: ProposalType;

  @IsOptional()
  @IsBoolean()
  isFeatured?: boolean;

  @IsOptional()
  @IsDateString()
  expiresAt?: Date;

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => AttachmentDto)
  attachments?: AttachmentDto[];

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CustomQuestionDto)
  customQuestions?: CustomQuestionDto[];

  @IsOptional()
  @IsNumber()
  successScore?: number;

  @IsOptional()
  @IsBoolean()
  isAutoGenerated?: boolean;
}