import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, CreateDateColumn, UpdateDateColumn } from 'typeorm';
import { Project } from '../projects/project.entity';

export enum ProposalStatus {
  PENDING = 'pending',
  ACCEPTED = 'accepted',
  REJECTED = 'rejected',
  WITHDRAWN = 'withdrawn',
  EXPIRED = 'expired'
}

export enum ProposalType {
  FIXED_PRICE = 'fixed_price',
  HOURLY = 'hourly',
  MILESTONE = 'milestone'
}

@Entity('proposals')
export class Proposal {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToOne(() => Project, project => project.proposals)
  project: Project;

  @Column()
  projectId: string;

  @Column()
  freelancerId: string;

  @Column({ type: 'text' })
  coverLetter: string;

  @Column({ type: 'decimal', precision: 10, scale: 2, nullable: true })
  proposedAmount: number;

  @Column({ type: 'int', nullable: true })
  estimatedHours: number;

  @Column({ type: 'int', nullable: true })
  estimatedDays: number;

  @Column({ type: 'simple-json', nullable: true })
  milestones: Array<{
    title: string;
    description: string;
    amount: number;
    dueDate: Date;
  }>;

  @Column({ type: 'varchar', length: 20, default: ProposalType.FIXED_PRICE })
  type: ProposalType;

  @Column({ type: 'varchar', length: 20, default: ProposalStatus.PENDING })
  status: ProposalStatus;

  @Column({ type: 'boolean', default: false })
  isFeatured: boolean;

  @Column({ type: 'datetime', nullable: true })
  acceptedAt: Date;

  @Column({ type: 'datetime', nullable: true })
  rejectedAt: Date;

  @Column({ type: 'datetime', nullable: true })
  withdrawnAt: Date;

  @Column({ type: 'datetime', nullable: true })
  expiresAt: Date;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  @Column({ type: 'simple-json', nullable: true })
  attachments: Array<{
    filename: string;
    url: string;
    type: string;
    size: number;
  }>;

  @Column({ type: 'simple-json', nullable: true })
  customQuestions: Array<{
    question: string;
    answer: string;
  }>;

  @Column({ type: 'decimal', precision: 3, scale: 2, nullable: true })
  successScore: number;

  @Column({ type: 'int', default: 0 })
  revisionCount: number;

  @Column({ type: 'boolean', default: false })
  isAutoGenerated: boolean;
}